#!/bin/bash

USER="$(ls /home/ | tr "\n" ' ' | awk '{print $1}')" # get the first user from home directory.
source /home/"$USER"/sh.library/color.sh

devices=$(xrandr -q | grep -w connected)
echo $devices

#xrandr --output HDMI-1 --primary --mode 1920x1080 --rotate normal --output DP-1 --mode 1920x1080 --rotate normal --left-of HDMI-1 --output eDP-1 --off
